.MODEL SMALL
.STACK 200H

.DATA ;WHERE WILL ALL VARIABLE WILL BE DECLARE

.CODE
MAIN PROC   ;INT MAIN()
    ;STATEMENT
    ;STATEMENT
    ;STATEMENT
    
    MOV AH,4CH
    INT 21H
MAIN ENDP   ;RETURN 0